# Building a Machine Learning Pipeline using Sklearn

The purpose of this notebook is to create a sklearn pipeline in order to make life a lot easier when scoring new data i.e. articles which have to undergo the same preprocessing and modeling strategy as the training data

## Import Modules

In [1]:
# import modules
from pathlib import Path
import numpy as np
import pandas as pd
from nltk import word_tokenize
from sklearn.model_selection import train_test_split          
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pickle
from sklearn.pipeline import Pipeline

## Set Path Variables

In [ ]:
# set path variables
DATAPATH = Path(Path.cwd().parents[0] / 'data')    
MODELPATH = Path(Path.cwd().parents[0] / 'model')

DATAPATH.mkdir(parents=True, exist_ok=True)
MODELPATH.mkdir(parents=True, exist_ok=True)

# Utility Functions

In [ ]:
def get_article_topic(pipeline_obj:Pipeline, article:pd.DataFrame, article_num:int):
    """Generate article topics for given article and given i.e. trained pipeline
    """
    topic_num = np.argmax(pipeline_obj.transform([article[article_num]]))
    return topic_num 

def get_topic_terms(lda_obj, cv_obj, topic_num=0, top_n=3):
    """ get the index position of the top 3 terms in a topic.
    input the fitted laten dirichtlet object.
    input the fitted count-vectorizer object.
    input the topic number.
    input the top-n words belonging to each topic.
    output the top_n words for topic_num. """
    return [cv_obj.get_feature_names_out()[ind] for ind in lda_obj.components_[topic_num].argsort()[-top_n:]]

## Import Data

In [ ]:
# import data
df = pd.read_csv(DATAPATH / "npr.csv")
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

## Define Custom Tokenizer Class 

In [ ]:
# write custom tokenizer class to be passed to CountVectorizer instance 
class LemmaTokenizer(object):
    def __init__(self):
        self.wnl = WordNetLemmatizer()
    def __call__(self, articles):
        lemma_tokens = [self.wnl.lemmatize(t) for t in word_tokenize(articles)]
        lemma_tokens_alpha = [t for t in lemma_tokens if t.isalpha()]
        return lemma_tokens_alpha

## Define Preprocessing and Modeling Pipeline

In [ ]:
# init pipeline object
pipe = Pipeline([('cv', CountVectorizer(lowercase=True,
                                        stop_words='english',
                                        tokenizer=LemmaTokenizer(),
                                        ngram_range=(1,1),
                                        max_df=.9, 
                                        min_df=.05,
                                        max_features=1000 
                                        )), 
                ('lda', LatentDirichletAllocation(n_components=10,
                                                  random_state=123,
                                                  n_jobs=-1))])

## Train and Test Split
We use a train test split to train the model on the training data and use the test data later on just for scoring kind of "new" data; the test data is of course not used by any means to test the model since it´s an unsupervised case with the ground truth being unknown 

In [ ]:
X_train, X_test = train_test_split(df, test_size=0.33, random_state=123)

In [ ]:
X_train.head()

Article
8854  Welcome to the third installment of Read, Watc...
3298  Milwaukee has the nation’s   publicly funded v...
8716  Donald Trump has released the names of his eco...
2246  South Korea and the U. S. confirm North Korea ...
7008  A   international convoy carrying desperately ...

In [ ]:
# reset index
X_test.reset_index(drop=True, inplace=True)

# save test data as csv file for later scoring
X_test.to_csv(DATAPATH /'npr_test.csv')

# Fit the Pipeline 

In [ ]:
# train the pipeline
pipe.fit(X_train.Article)

c:\Users\Nutzer\.conda\envs\NLP\lib\site-packages\sklearn\feature_extraction\text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  warnings.warn(


Pipeline(steps=[('cv',
                 CountVectorizer(max_df=0.9, max_features=1000, min_df=0.05,
                                 stop_words='english',
                                 tokenizer=<__main__.LemmaTokenizer object at 0x000001FABAAEB9A0>)),
                ('lda',
                 LatentDirichletAllocation(n_jobs=-1, random_state=123))])

# Evaluate the functionality of the fitted pipeline and all its components

In [ ]:
# check the whole pipeline ie apply it to the first article...we expect an array with topic probabilities
pipe.transform([X_train['Article'][0]])

array([[2.62531627e-04, 4.65037559e-02, 2.62546482e-04, 2.62537780e-04,
        1.00218759e-02, 1.02570214e-02, 2.25746589e-01, 5.96689075e-01,
        1.09731526e-01, 2.62541382e-04]])

In [ ]:
# check the count vectorizer part of the pipeline ie apply it to the first article
dtm = pipe['cv'].transform([X_train['Article'][0]])
dtm

<1x982 sparse matrix of type '<class 'numpy.int64'>'
	with 200 stored elements in Compressed Sparse Row format>

In [ ]:
# get the terms
pipe['cv'].get_feature_names()[-10:]

c:\Users\Nutzer\.conda\envs\NLP\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['writer',
 'writes',
 'writing',
 'written',
 'wrong',
 'wrote',
 'year',
 'yes',
 'york',
 'young']

In [ ]:
# check the lda part of the pipeline ie apply it to the first article
pipe['lda'].transform(dtm)

array([[2.62531627e-04, 4.65037559e-02, 2.62546482e-04, 2.62537780e-04,
        1.00218759e-02, 1.02570214e-02, 2.25746589e-01, 5.96689075e-01,
        1.09731526e-01, 2.62541382e-04]])

In [ ]:
# have a look at the fit result i.e. the topics
pipe['lda'].components_[:10]

array([[1.16714856e+02, 3.27118513e+02, 1.17011295e+02, ...,
        4.31424922e+01, 7.75681291e+01, 1.51622774e+02],
       [4.00207571e+00, 2.37107902e+02, 2.35638090e+01, ...,
        3.59692814e+01, 3.79640883e+01, 1.06638151e+03],
       [6.23051191e+01, 1.96629786e+02, 2.66533702e+02, ...,
        6.24960998e-01, 3.79418747e+02, 1.11845916e-01],
       ...,
       [5.83608016e+01, 1.53166513e+02, 3.14981981e+01, ...,
        7.31516152e+01, 1.05656930e+02, 7.65427268e+01],
       [6.33116321e+01, 1.10166890e+02, 9.50284159e+01, ...,
        1.21652565e+01, 3.02962729e+02, 1.41992550e+01],
       [8.45376349e+01, 3.47856905e+02, 1.97655330e+01, ...,
        2.98919634e+02, 6.92465185e+02, 6.89328443e+02]])

## Score New Data 

In [ ]:
X_test.head()

Article
6807  Hamilton, the Broadway musical about ”the scra...
4640  Tennessee Ernie Ford was fed up with the trapp...
3160  When Yomi Wrong was born in 1972, doctors told...
6476  As laptops become smaller and more ubiquitous,...
9379  Republican presidential nominee Donald Trump i...

In [ ]:
# get article topic for single article
article_num = 0
top_n = 10
topic_num = get_article_topic(pipe, X_test.Article, article_num)
top_terms = get_topic_terms(lda_obj=pipe['lda'], cv_obj=pipe['cv'], topic_num=topic_num, top_n=top_n)
print('The main topic for article #{} is topic #{}'.format(article_num, topic_num))
print('The top {} terms for topic #{} are: \n {}'.format(top_n, topic_num, top_terms))
print('\n')

The main topic for article #0 is topic #9
The top 10 terms for topic #9 are: 
 ['know', 'ha', 'people', 'year', 'say', 'time', 'just', 'like', 't', 'wa']


